[package]
name = "pry"
version = "0.1.0"
edition = "2021"

[dependencies]
# smol = "1.2"
# tracing = "0.1"
# tracing_subscriber = "0.3"
# futures = "0.3"
# rayon = "1.5"
# parking_lot = "0.12"
once_cell = "1.18"
hashbrown = "0.14"
twox-hash = "1.6"
# anyhow = "1.0"

fst = "0.4"
combine = "4.6"
# regex-automata = { version = "0.3" }
memmap2 = "0.7"
logos = "0.13"
roaring = "0.10"
# serde = { version = "1", features = ["derive"]}
# serde_json = "1"

[profile.bench]
opt = 3
debug = false
debug-assertions = false

[profile.release]
opt = 3
lto = true
debug = false
debug-assertions = false
strip = true
